package org.campagnelab.circles.persistence.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This interface is not involved in the actual method invocation
 */
@Deprecated
public interface IIncludeConcepts_BehaviorDescriptor {
  public Iterable<SNode> virtual_getConcepts_1004539053072256506(SNode thisNode);
}
