package org.campagnelab.circles.persistence.behavior;

/*Generated by MPS */


/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class IIncludeConcepts_Behavior {
}
