package org.campagnelab.circles.aspect.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Collections;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x34e5376c6d3f8e17L, "org.campagnelab.circles.aspect.structure.Apache2_0"))) {
        return Collections.<ConceptEditor>singletonList(new Apache2_0_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x4c2903f10155d7d9L, "org.campagnelab.circles.aspect.structure.CellModel_ActionLink"))) {
        return Collections.<ConceptEditor>singletonList(new CellModel_ActionLink_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x4ff6b12e4c43d11bL, "org.campagnelab.circles.aspect.structure.CellModel_Link"))) {
        return Collections.<ConceptEditor>singletonList(new CellModel_Link_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x226122c3adaae177L, "org.campagnelab.circles.aspect.structure.ChildrenInitialization"))) {
        return Collections.<ConceptEditor>singletonList(new ChildrenInitialization_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x2970c96b0e706973L, "org.campagnelab.circles.aspect.structure.Database"))) {
        return Collections.<ConceptEditor>singletonList(new Database_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x73b7c6f9c8921ad7L, "org.campagnelab.circles.aspect.structure.DbRetrievedFocus"))) {
        return Collections.<ConceptEditor>singletonList(new DbRetrievedFocus_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x15998bfb2b1eb1ecL, "org.campagnelab.circles.aspect.structure.EditorRef"))) {
        return Collections.<ConceptEditor>singletonList(new EditorRef_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x679f435be67a4016L, "org.campagnelab.circles.aspect.structure.ExcludeConcept"))) {
        return Collections.<ConceptEditor>singletonList(new ExcludeConcept_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x43079579be16c5ecL, "org.campagnelab.circles.aspect.structure.GwtModule"))) {
        return Collections.<ConceptEditor>singletonList(new GwtModule_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x658b57cc0dc71a3eL, "org.campagnelab.circles.aspect.structure.GwtModuleRef"))) {
        return Collections.<ConceptEditor>singletonList(new GwtModuleRef_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x34e5376c6d3f1e95L, "org.campagnelab.circles.aspect.structure.GwtPomBuild"))) {
        return Collections.<ConceptEditor>singletonList(new GwtPomBuild_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x658b57cc0dde1cebL, "org.campagnelab.circles.aspect.structure.HtmlDocument"))) {
        return Collections.<ConceptEditor>singletonList(new HtmlDocument_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x42f48c9f1414cf69L, "org.campagnelab.circles.aspect.structure.IncludeConcepts"))) {
        return Collections.<ConceptEditor>singletonList(new IncludeConcepts_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0xdf0d6f24d611395L, "org.campagnelab.circles.aspect.structure.IncludeLanguage"))) {
        return Collections.<ConceptEditor>singletonList(new IncludeLanguage_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x26a2ac35a827beb2L, "org.campagnelab.circles.aspect.structure.InterfaceMethod"))) {
        return Collections.<ConceptEditor>singletonList(new InterfaceMethod_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x34e5376c6d3f8da8L, "org.campagnelab.circles.aspect.structure.License"))) {
        return Collections.<ConceptEditor>singletonList(new License_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x4dafaaf043fb6447L, "org.campagnelab.circles.aspect.structure.LiteralPropertyValue"))) {
        return Collections.<ConceptEditor>singletonList(new LiteralPropertyValue_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x226122c3ae481192L, "org.campagnelab.circles.aspect.structure.MapChild"))) {
        return Collections.<ConceptEditor>singletonList(new MapChild_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x34e5376c6d3a80a5L, "org.campagnelab.circles.aspect.structure.MavenArtifactInfo"))) {
        return Collections.<ConceptEditor>singletonList(new MavenArtifactInfo_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x34e5376c6d3a7fc5L, "org.campagnelab.circles.aspect.structure.MavenDependency"))) {
        return Collections.<ConceptEditor>singletonList(new MavenDependency_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x34e5376c6d3a5ef3L, "org.campagnelab.circles.aspect.structure.MavenPom"))) {
        return Collections.<ConceptEditor>singletonList(new MavenPom_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x34e5376c6d3f1e94L, "org.campagnelab.circles.aspect.structure.MavenPomBuildSection"))) {
        return Collections.<ConceptEditor>singletonList(new MavenPomBuildSection_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x26a2ac35a824df3bL, "org.campagnelab.circles.aspect.structure.Methods"))) {
        return Collections.<ConceptEditor>singletonList(new Methods_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x73b7c6f9c8921ad6L, "org.campagnelab.circles.aspect.structure.NewBeanCreationFocus"))) {
        return Collections.<ConceptEditor>singletonList(new NewBeanCreationFocus_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x42f48c9f1414cf63L, "org.campagnelab.circles.aspect.structure.PersistedConcepts"))) {
        return Collections.<ConceptEditor>singletonList(new PersistedConcepts_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x658b57cc0e19886eL, "org.campagnelab.circles.aspect.structure.Place"))) {
        return Collections.<ConceptEditor>singletonList(new Place_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x658b57cc0e19887aL, "org.campagnelab.circles.aspect.structure.PlaceRef"))) {
        return Collections.<ConceptEditor>singletonList(new PlaceRef_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x4dafaaf043bc6a83L, "org.campagnelab.circles.aspect.structure.PropertyInitialization"))) {
        return Collections.<ConceptEditor>singletonList(new PropertyInitialization_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x26614b7e602adaf8L, "org.campagnelab.circles.aspect.structure.QueryArgument"))) {
        return Collections.<ConceptEditor>singletonList(new QueryArgument_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x26614b7e602adaf2L, "org.campagnelab.circles.aspect.structure.QueryKind"))) {
        return Collections.<ConceptEditor>singletonList(new QueryKind_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x26614b7e602adaf3L, "org.campagnelab.circles.aspect.structure.QueryReturnType"))) {
        return Collections.<ConceptEditor>singletonList(new QueryReturnType_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x658b57cc0e198871L, "org.campagnelab.circles.aspect.structure.Token"))) {
        return Collections.<ConceptEditor>singletonList(new Token_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x2888d0d3c5ebf504L, "org.campagnelab.circles.aspect.structure.TokenConstantValue"))) {
        return Collections.<ConceptEditor>singletonList(new TokenConstantValue_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x4dafaaf043f5ef7cL, "org.campagnelab.circles.aspect.structure.TokenPropertyValue"))) {
        return Collections.<ConceptEditor>singletonList(new TokenPropertyValue_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x73b7c6f9c8921ad9L, "org.campagnelab.circles.aspect.structure.TokenRef"))) {
        return Collections.<ConceptEditor>singletonList(new TokenRef_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x4c2903f1016e47e7L, "org.campagnelab.circles.aspect.structure.UserMethodReference"))) {
        return Collections.<ConceptEditor>singletonList(new UserMethodReference_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x658b57cc0e1e2264L, "org.campagnelab.circles.aspect.structure.ViewNodeActivity"))) {
        return Collections.<ConceptEditor>singletonList(new ViewNodeActivity_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x15998bfb2b1eb1ebL, "org.campagnelab.circles.aspect.structure.WebEditors"))) {
        return Collections.<ConceptEditor>singletonList(new WebEditors_Editor());
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }



}
