package org.campagnelab.circles.aspect.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Collections;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x34e5376c6d3f8e17L, "org.campagnelab.circles.aspect.structure.Apache2_0"))) {
        return Collections.<ConceptEditor>singletonList(new Apache2_0_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x2970c96b0e706973L, "org.campagnelab.circles.aspect.structure.Database"))) {
        return Collections.<ConceptEditor>singletonList(new Database_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x34e5376c6d3f1e95L, "org.campagnelab.circles.aspect.structure.GwtPomBuild"))) {
        return Collections.<ConceptEditor>singletonList(new GwtPomBuild_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x42f48c9f1414cf69L, "org.campagnelab.circles.aspect.structure.IncludeConcepts"))) {
        return Collections.<ConceptEditor>singletonList(new IncludeConcepts_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0xdf0d6f24d611395L, "org.campagnelab.circles.aspect.structure.IncludeLanguage"))) {
        return Collections.<ConceptEditor>singletonList(new IncludeLanguage_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x34e5376c6d3a80a5L, "org.campagnelab.circles.aspect.structure.MavenArtifactInfo"))) {
        return Collections.<ConceptEditor>singletonList(new MavenArtifactInfo_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x34e5376c6d3a7fc5L, "org.campagnelab.circles.aspect.structure.MavenDependency"))) {
        return Collections.<ConceptEditor>singletonList(new MavenDependency_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x34e5376c6d3a5ef3L, "org.campagnelab.circles.aspect.structure.MavenPom"))) {
        return Collections.<ConceptEditor>singletonList(new MavenPom_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x34e5376c6d3f1e94L, "org.campagnelab.circles.aspect.structure.MavenPomBuildSection"))) {
        return Collections.<ConceptEditor>singletonList(new MavenPomBuildSection_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x42f48c9f1414cf63L, "org.campagnelab.circles.aspect.structure.PersistedConcepts"))) {
        return Collections.<ConceptEditor>singletonList(new PersistedConcepts_Editor());
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }



}
