package org.campagnelab.circles.aspect.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.openapi.editor.EditorContext;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;
import jetbrains.mps.lang.editor.cellProviders.SingleRoleCellProvider;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.nodeEditor.cellMenu.DefaultChildSubstituteInfo;

public class ViewNodeActivity_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_qvjxkb_a(editorContext, node);
  }
  private EditorCell createCollection_qvjxkb_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_qvjxkb_a");
    editorCell.setBig(true);
    editorCell.addEditorCell(this.createConstant_qvjxkb_a0(editorContext, node));
    editorCell.addEditorCell(this.createRefNode_qvjxkb_b0(editorContext, node));
    return editorCell;
  }
  private EditorCell createConstant_qvjxkb_a0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "View node, obtained with");
    editorCell.setCellId("Constant_qvjxkb_a0");
    editorCell.setDefaultText("");
    return editorCell;
  }
  private EditorCell createRefNode_qvjxkb_b0(EditorContext editorContext, SNode node) {
    SingleRoleCellProvider provider = new ViewNodeActivity_Editor.focusSingleRoleHandler_qvjxkb_b0(node, MetaAdapterFactory.getContainmentLink(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x658b57cc0e1e2264L, 0x73b7c6f9c8921ae1L, "focus"), editorContext);
    return provider.createCell();
  }
  private class focusSingleRoleHandler_qvjxkb_b0 extends SingleRoleCellProvider {
    public focusSingleRoleHandler_qvjxkb_b0(SNode ownerNode, SContainmentLink containmentLink, EditorContext context) {
      super(ownerNode, containmentLink, context);
    }
    protected EditorCell createChildCell(SNode child) {
      EditorCell editorCell = super.createChildCell(child);
      installCellInfo(child, editorCell);
      return editorCell;
    }
    private void installCellInfo(SNode child, EditorCell editorCell) {
      editorCell.setSubstituteInfo(new DefaultChildSubstituteInfo(myOwnerNode, myContainmentLink.getDeclarationNode(), myEditorContext));
      if (editorCell.getRole() == null) {
        editorCell.setRole("focus");
      }
    }
    @Override
    protected EditorCell createEmptyCell() {
      EditorCell editorCell = super.createEmptyCell();
      editorCell.setCellId("empty_focus");
      installCellInfo(null, editorCell);
      return editorCell;
    }
    protected String getNoTargetText() {
      return "<no focus>";
    }
  }
}
