package org.campagnelab.circles.aspect.runtime;

/*Generated by MPS */

import com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx;
import org.apache.log4j.Level;
import com.orientechnologies.orient.core.query.live.OLiveQueryHook;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;

public class DbAccess {
  public static ODatabaseDocumentTx openDb(String url, String user, String password) {
    ODatabaseDocumentTx db;
    db = new ODatabaseDocumentTx(url);
    if (url.startsWith("plocal:") && !((db.exists()))) {
      if (LOG.isEnabledFor(Level.WARN)) {
        LOG.warn("Database did not exist");
      }
      return null;
    } else {
      db.open(user, password);
      db.activateOnCurrentThread();
      return db;
    }
  }
  public static ODatabaseDocumentTx openCreateDb(String url, String user, String password) {
    ODatabaseDocumentTx db;
    db = new ODatabaseDocumentTx(url);
    if (url.startsWith("plocal:") && !((db.exists()))) {
      if (LOG.isInfoEnabled()) {
        LOG.info("Database did not exist, creating new one");
      }
      db.create();
      db.registerHook(new OLiveQueryHook(db));
    } else {
      db.open(user, password);
    }
    db.activateOnCurrentThread();
    return db;
  }
  public static void closeDb(ODatabaseDocumentTx db) {
    if (db != null) {
      db.close();
    }
  }

  protected static Logger LOG = LogManager.getLogger(DbAccess.class);
}
