package org.campagnelab.circles.aspect.runtime;

/*Generated by MPS */


public enum FIELDS {
  ID() {
    public String dbName() {
      return "id";
    }

  },
  NAME() {
    public String dbName() {
      return "name";
    }

  },
  CHILDREN() {
    public String dbName() {
      return "children";
    }

  },
  PARENT() {
    public String dbName() {
      return "parent";
    }

  };

  public abstract String dbName();
}
