package org.campagnelab.circles.model;

/*Generated by MPS */

import jetbrains.mps.smodel.language.LanguageRuntime;
import jetbrains.mps.smodel.adapter.ids.SLanguageId;
import java.util.UUID;
import java.util.Collection;
import jetbrains.mps.generator.runtime.TemplateModule;
import jetbrains.mps.smodel.runtime.ILanguageAspect;
import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import org.campagnelab.circles.model.editor.EditorAspectDescriptorImpl;
import jetbrains.mps.smodel.runtime.StructureAspectDescriptor;
import org.campagnelab.circles.aspect.runtime.WebLanguageAspectDescriptor;
import org.campagnelab.circles.model.web.WebAspectDescriptor;

public class Language extends LanguageRuntime {
  public static String MODULE_REF = "87c8043e-fece-4ba6-9d13-3ef71e47af25(org.campagnelab.circles.model)";
  public Language() {
  }
  @Override
  public String getNamespace() {
    return "org.campagnelab.circles.model";
  }

  @Override
  public int getVersion() {
    return 0;
  }

  public SLanguageId getId() {
    return new SLanguageId(UUID.fromString("87c8043e-fece-4ba6-9d13-3ef71e47af25"));
  }
  @Override
  protected String[] getExtendedLanguageIDs() {
    return new String[]{"jetbrains.mps.lang.core"};
  }
  @Override
  public Collection<TemplateModule> getGenerators() {
    return null;
  }
  @Override
  protected <T extends ILanguageAspect> T createAspect(Class<T> aspectClass) {
    if (aspectClass == EditorAspectDescriptor.class) {
      return (T) new EditorAspectDescriptorImpl();
    }
    if (aspectClass == StructureAspectDescriptor.class) {
      return (T) new org.campagnelab.circles.model.structure.StructureAspectDescriptor();
    }
    if (aspectClass.getName().equals("org.campagnelab.circles.aspect.runtime.WebLanguageAspectDescriptor")) {
      if (aspectClass == WebLanguageAspectDescriptor.class) {
        return (T) new WebAspectDescriptor();
      }
    }
    return super.createAspect(aspectClass);
  }
}
