package org.webapp.languages.jetbrains_mps_lang_core.shared.beans;

/*Generated by MPS */

import java.io.Serializable;

public class BaseConcept_Bean implements Serializable {
  public BaseConcept_Bean() {
    String shortDescription;
    String alias;
    String virtualPackage;
  }
}
