package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import org.webapp.languages.jetbrains_mps_lang_core.shared.beans.BaseConcept_Bean;
import java.io.Serializable;
import java.util.List;

public class AllCirclesInDb_Bean extends BaseConcept_Bean implements Serializable {
  public List<Circle_Bean> circles;
  public AllCirclesInDb_Bean() {
  }
}
