package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import jetbrains.jetpad.mapper.gwt.BaseWithElement;
import com.google.gwt.core.client.GWT;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.dom.client.UListElement;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.dom.client.DivElement;

public class AllCirclesInDb_WebView extends BaseWithElement {
  private static final AllCirclesInDb_WebView.ViewUiBinder ourUiBinder = GWT.create(AllCirclesInDb_WebView.ViewUiBinder.class);
  @UiField
  public UListElement circles;


  public AllCirclesInDb_WebView() {
    setElement(ourUiBinder.createAndBindUi(this));
  }
  /*package*/ static interface ViewUiBinder extends UiBinder<DivElement, AllCirclesInDb_WebView> {
  }

}
