package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import java.util.logging.Logger;
import jetbrains.jetpad.model.collections.list.ObservableList;
import org.webapp.languages.jetbrains_mps_lang_core.client.models.BaseConcept_WebModel;
import jetbrains.jetpad.model.children.ChildList;

public class BaseCommentAttribute_WebModel extends ChildAttribute_WebModel {
  protected ClientFactoryInterface clientFactory;
  protected static Logger logger = Logger.getLogger("BaseCommentAttribute_WebModel");

  public void setClientFactory(ClientFactoryInterface cf) {
    this.clientFactory = cf;
  }
  public ObservableList<BaseConcept_WebModel> commentedNode = new ChildList(this);

  public BaseCommentAttribute_WebModel() {

  }
}
