package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import java.util.logging.Logger;

public class ChildAttributeToWebModel {
  private static Logger logger = Logger.getLogger("ChildAttributeToWebModel");

  public static ChildAttribute_WebModel create(ChildAttribute_Bean bean) {
    ChildAttribute_WebModel model = (ChildAttribute_WebModel) WebModelFactory.createWebModel(bean);
    return model;
  }
  public static void transfer(ChildAttribute_Bean source, ChildAttribute_WebModel destination) {
    if (source == null) {
      return;
    }
    AttributeToWebModel.transfer(source, destination);
    destination.linkRole.set(source.linkRole);
    destination.linkId.set(source.linkId);
    // transfer children: 
    // transfer references: 

  }

  public static ChildAttribute_WebModel transform(ChildAttribute_Bean bean, ClientFactoryInterface clientFactory) {
    if (bean == null) {
      return null;
    }
    ChildAttribute_WebModel model = create(bean);
    if (model != null) {
      model.setClientFactory(clientFactory);
    }
    transfer(bean, model);
    return model;
  }
}
