package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import org.webapp.languages.jetbrains_mps_lang_core.client.models.BaseConcept_WebModel;
import java.util.logging.Logger;
import jetbrains.jetpad.model.property.Property;
import jetbrains.jetpad.model.property.ValueProperty;
import jetbrains.jetpad.model.children.ChildProperty;

public class CircleRef_WebModel extends BaseConcept_WebModel {
  protected ClientFactoryInterface clientFactory;
  protected static Logger logger = Logger.getLogger("CircleRef_WebModel");

  public void setClientFactory(ClientFactoryInterface cf) {
    this.clientFactory = cf;
  }
  public final Property<String> queryTerm = new ValueProperty();
  public ChildProperty circle = new ChildProperty(this);

  public CircleRef_WebModel() {

  }
}
