package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import org.webapp.languages.jetbrains_mps_lang_core.shared.beans.BaseConcept_Bean;
import java.io.Serializable;
import java.util.List;

public class Circle_Bean extends BaseConcept_Bean implements Serializable {
  public String query;
  public String name;
  public String id;
  public List<CircleRef_Bean> containedCircles;
  public List<CircleItem_Bean> items;
  public Circle_Bean() {
  }
}
