package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import jetbrains.jetpad.mapper.gwt.BaseWithElement;
import com.google.gwt.core.client.GWT;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.dom.client.DivElement;

public class CircleRef_WebView extends BaseWithElement {
  private static final CircleRef_WebView.ViewUiBinder ourUiBinder = GWT.create(CircleRef_WebView.ViewUiBinder.class);
  @UiField
  public SpanElement name;
  @UiField
  public SpanElement id;
  @UiField
  public SpanElement queryTerm;


  public CircleRef_WebView() {
    setElement(ourUiBinder.createAndBindUi(this));
  }
  /*package*/ static interface ViewUiBinder extends UiBinder<DivElement, CircleRef_WebView> {
  }

}
