package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import org.webapp.languages.jetbrains_mps_lang_core.shared.beans.BaseConcept_Bean;
import java.io.Serializable;

public class CircleRef_Bean extends BaseConcept_Bean implements Serializable {
  public String queryTerm;
  public Circle_Bean circle;
  public CircleRef_Bean() {
  }
}
