package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import jetbrains.jetpad.mapper.gwt.BaseWithElement;
import com.google.gwt.core.client.GWT;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.dom.client.SpanElement;
import com.google.gwt.dom.client.UListElement;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.dom.client.DivElement;

public class CircleContainer_WebView extends BaseWithElement {
  private static final CircleContainer_WebView.ViewUiBinder ourUiBinder = GWT.create(CircleContainer_WebView.ViewUiBinder.class);
  @UiField
  public SpanElement query;
  @UiField
  public UListElement containedCircles;


  public CircleContainer_WebView() {
    setElement(ourUiBinder.createAndBindUi(this));
  }
  /*package*/ static interface ViewUiBinder extends UiBinder<DivElement, CircleContainer_WebView> {
  }

}
