package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import jetbrains.jetpad.mapper.Mapper;
import jetbrains.jetpad.mapper.Synchronizers;
import jetbrains.jetpad.mapper.gwt.DomUtil;

public class CircleItem_WebMapper extends Mapper<CircleItem_WebModel, CircleItem_WebView> {

  public CircleItem_WebMapper(CircleItem_WebModel model) {
    super(model, new CircleItem_WebView());
    // Connect events to view here 
  }
  @Override
  protected void registerSynchronizers(Mapper.SynchronizersConfiguration conf) {
    super.registerSynchronizers(conf);
    //  Insertion point for add synchronizer: 
    conf.add(Synchronizers.forPropsTwoWay(getSource().name, DomUtil.editableTextOf(getTarget().name)));

    //  map references like %circles% -> name 



  }

}
