package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import java.util.logging.Logger;

public class CircleItemToWebModel {
  private static Logger logger = Logger.getLogger("CircleItemToWebModel");

  public static CircleItem_WebModel create(CircleItem_Bean bean) {
    CircleItem_WebModel model = (CircleItem_WebModel) WebModelFactory.createWebModel(bean);
    return model;
  }
  public static void transfer(CircleItem_Bean source, CircleItem_WebModel destination) {
    if (source == null) {
      return;
    }
    BaseConceptToWebModel.transfer(source, destination);
    
    // ignore interface ;
    destination.name.set(source.name);
    // transfer children: 
    // transfer references: 

  }

  public static CircleItem_WebModel transform(CircleItem_Bean bean, ClientFactoryInterface clientFactory) {
    if (bean == null) {
      return null;
    }
    CircleItem_WebModel model = create(bean);
    if (model != null) {
      model.setClientFactory(clientFactory);
    }
    transfer(bean, model);
    return model;
  }
}
