package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import java.util.logging.Logger;
import jetbrains.jetpad.model.property.Property;
import jetbrains.jetpad.model.property.ValueProperty;

public class ExportScopeNamespace_WebModel extends ExportScope_WebModel {
  protected ClientFactoryInterface clientFactory;
  protected static Logger logger = Logger.getLogger("ExportScopeNamespace_WebModel");

  public void setClientFactory(ClientFactoryInterface cf) {
    this.clientFactory = cf;
  }
  public final Property<String> namespace = new ValueProperty();

  public ExportScopeNamespace_WebModel() {

  }
}
