package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import java.util.logging.Logger;

public class ExportScopeToWebModel {
  private static Logger logger = Logger.getLogger("ExportScopeToWebModel");

  public static ExportScope_WebModel create(ExportScope_Bean bean) {
    ExportScope_WebModel model = (ExportScope_WebModel) WebModelFactory.createWebModel(bean);
    return model;
  }
  public static void transfer(ExportScope_Bean source, ExportScope_WebModel destination) {
    if (source == null) {
      return;
    }
    NodeAttributeToWebModel.transfer(source, destination);
    
    // ignore interface ;
    // transfer children: 
    // transfer references: 

  }

  public static ExportScope_WebModel transform(ExportScope_Bean bean, ClientFactoryInterface clientFactory) {
    if (bean == null) {
      return null;
    }
    ExportScope_WebModel model = create(bean);
    if (model != null) {
      model.setClientFactory(clientFactory);
    }
    transfer(bean, model);
    return model;
  }
}
