package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import java.util.logging.Logger;

public class ExportScopeModuleToWebModel {
  private static Logger logger = Logger.getLogger("ExportScopeModuleToWebModel");

  public static ExportScopeModule_WebModel create(ExportScopeModule_Bean bean) {
    ExportScopeModule_WebModel model = (ExportScopeModule_WebModel) WebModelFactory.createWebModel(bean);
    return model;
  }
  public static void transfer(ExportScopeModule_Bean source, ExportScopeModule_WebModel destination) {
    if (source == null) {
      return;
    }
    ExportScopeToWebModel.transfer(source, destination);
    // transfer children: 
    // transfer references: 

  }

  public static ExportScopeModule_WebModel transform(ExportScopeModule_Bean bean, ClientFactoryInterface clientFactory) {
    if (bean == null) {
      return null;
    }
    ExportScopeModule_WebModel model = create(bean);
    if (model != null) {
      model.setClientFactory(clientFactory);
    }
    transfer(bean, model);
    return model;
  }
}
