package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import java.io.Serializable;

public class ExportScopeNamespace_Bean extends ExportScope_Bean implements Serializable {
  public String namespace;
  public ExportScopeNamespace_Bean() {
  }
}
