package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import java.io.Serializable;

public class ExportScopePublic_Bean extends ExportScope_Bean implements Serializable {
  public ExportScopePublic_Bean() {
  }
}
