package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import java.util.logging.Logger;

public class FileItemToWebModel {
  private static Logger logger = Logger.getLogger("FileItemToWebModel");

  public static FileItem_WebModel create(FileItem_Bean bean) {
    FileItem_WebModel model = (FileItem_WebModel) WebModelFactory.createWebModel(bean);
    return model;
  }
  public static void transfer(FileItem_Bean source, FileItem_WebModel destination) {
    if (source == null) {
      return;
    }
    CircleItemToWebModel.transfer(source, destination);
    destination.name.set(source.name);
    destination.path.set(source.path);
    destination.hostname.set(source.hostname);
    // transfer children: 
    // transfer references: 

  }

  public static FileItem_WebModel transform(FileItem_Bean bean, ClientFactoryInterface clientFactory) {
    if (bean == null) {
      return null;
    }
    FileItem_WebModel model = create(bean);
    if (model != null) {
      model.setClientFactory(clientFactory);
    }
    transfer(bean, model);
    return model;
  }
}
