package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import java.io.Serializable;

public class FileItem_Bean extends CircleItem_Bean implements Serializable {
  public String name;
  public String path;
  public String hostname;
  public FileItem_Bean() {
  }
}
