package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import java.io.Serializable;

public class IDontApplyTypesystemRules_Bean implements Serializable {
  public IDontApplyTypesystemRules_Bean() {
  }
}
