package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import java.io.Serializable;

public class PropertyAttribute_Bean extends Attribute_Bean implements Serializable {
  public String propertyName;
  public String propertyId;
  public PropertyAttribute_Bean() {
  }
}
