package org.campagnelab.circles.mockup.web;

/*Generated by MPS */

import org.campagnelab.circles.aspect.runtime.WebLanguageAspectDescriptor;
import org.apache.log4j.Level;
import org.apache.log4j.Logger;
import org.apache.log4j.LogManager;

public class WebAspectDescriptor implements WebLanguageAspectDescriptor {
  public WebAspectDescriptor() {
    dbHelper = new DbSchemaHelper("plocal:/usr/local/dbs/test6");
  }
  private DbSchemaHelper dbHelper;
  public void defineSchemaForConcepts() {
    if (LOG.isInfoEnabled()) {
      LOG.info("Starting defineSchemaForConcepts for " + "plocal:/usr/local/dbs/test6");
    }
    try {
      dbHelper.defineSchemaForConcepts();
    } catch (Throwable t) {
      if (LOG.isEnabledFor(Level.ERROR)) {
        LOG.error("Unable to define schema:", t);
      }
    }
  }
  protected static Logger LOG = LogManager.getLogger(WebAspectDescriptor.class);
}
