package org.campagnelab.circles.mockup.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class AllCirclesInDb_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public AllCirclesInDb_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.circles.mockup.structure.AllCirclesInDb";
  }
}
