package org.campagnelab.circles.mockup.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class Dashboard_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements CircleContainer_BehaviorDescriptor {
  public Dashboard_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.circles.mockup.structure.Dashboard";
  }
}
