package org.campagnelab.circles.mockup.behavior;

/*Generated by MPS */


public class FileItem_BehaviorDescriptor extends CircleItem_BehaviorDescriptor {
  public FileItem_BehaviorDescriptor() {
  }
  @Override
  public String getConceptFqName() {
    return "org.campagnelab.circles.mockup.structure.FileItem";
  }
}
