package org.campagnelab.circles.aspect.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBehaviorAspectDescriptor;
import jetbrains.mps.core.aspects.behaviour.api.BHDescriptor;
import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import java.util.Arrays;

public final class BehaviorAspectDescriptor extends BaseBehaviorAspectDescriptor {
  private final BHDescriptor myIIncludeConcepts__BehaviorDescriptor = new IIncludeConcepts__BehaviorDescriptor();
  private final BHDescriptor myIncludeLanguage__BehaviorDescriptor = new IncludeLanguage__BehaviorDescriptor();
  private final BHDescriptor myWebEditors__BehaviorDescriptor = new WebEditors__BehaviorDescriptor();
  private final BHDescriptor myNListFocus__BehaviorDescriptor = new NListFocus__BehaviorDescriptor();
  private final BHDescriptor myMapChild__BehaviorDescriptor = new MapChild__BehaviorDescriptor();
  private final BHDescriptor myQueryReturnType__BehaviorDescriptor = new QueryReturnType__BehaviorDescriptor();
  private final BHDescriptor myInterfaceMethod__BehaviorDescriptor = new InterfaceMethod__BehaviorDescriptor();
  private final BHDescriptor myMavenPom__BehaviorDescriptor = new MavenPom__BehaviorDescriptor();
  private final BHDescriptor myApache2_0__BehaviorDescriptor = new Apache2_0__BehaviorDescriptor();
  private final BHDescriptor myPersistedConcepts__BehaviorDescriptor = new PersistedConcepts__BehaviorDescriptor();
  private final BHDescriptor myIncludeConcepts__BehaviorDescriptor = new IncludeConcepts__BehaviorDescriptor();
  private final BHDescriptor myGwtModule__BehaviorDescriptor = new GwtModule__BehaviorDescriptor();
  private final BHDescriptor myTokenValueLink__BehaviorDescriptor = new TokenValueLink__BehaviorDescriptor();
  private final BHDescriptor myCellModel_Link__BehaviorDescriptor = new CellModel_Link__BehaviorDescriptor();
  private final BHDescriptor myExcludeConcept__BehaviorDescriptor = new ExcludeConcept__BehaviorDescriptor();
  private final BHDescriptor myIExcludeConcepts__BehaviorDescriptor = new IExcludeConcepts__BehaviorDescriptor();
  private final BHDescriptor myNodeFocus__BehaviorDescriptor = new NodeFocus__BehaviorDescriptor();
  private final BHDescriptor myNewBeanCreationFocus__BehaviorDescriptor = new NewBeanCreationFocus__BehaviorDescriptor();
  private final BHDescriptor myDbRetrievedFocus__BehaviorDescriptor = new DbRetrievedFocus__BehaviorDescriptor();

  private final long[] myConceptBehaviorIds;

  public BehaviorAspectDescriptor() {
    myConceptBehaviorIds = new long[19];
    myConceptBehaviorIds[0] = 0xdf0d6f24d610de2L;
    myConceptBehaviorIds[1] = 0xdf0d6f24d611395L;
    myConceptBehaviorIds[2] = 0x15998bfb2b1eb1ebL;
    myConceptBehaviorIds[3] = 0x226122c3ae44d492L;
    myConceptBehaviorIds[4] = 0x226122c3ae481192L;
    myConceptBehaviorIds[5] = 0x26614b7e602adaf3L;
    myConceptBehaviorIds[6] = 0x26a2ac35a827beb2L;
    myConceptBehaviorIds[7] = 0x34e5376c6d3a5ef3L;
    myConceptBehaviorIds[8] = 0x34e5376c6d3f8e17L;
    myConceptBehaviorIds[9] = 0x42f48c9f1414cf63L;
    myConceptBehaviorIds[10] = 0x42f48c9f1414cf69L;
    myConceptBehaviorIds[11] = 0x43079579be16c5ecL;
    myConceptBehaviorIds[12] = 0x4dafaaf043f5ef79L;
    myConceptBehaviorIds[13] = 0x4ff6b12e4c43d11bL;
    myConceptBehaviorIds[14] = 0x679f435be67a4016L;
    myConceptBehaviorIds[15] = 0x679f435be67c6f7aL;
    myConceptBehaviorIds[16] = 0x73b7c6f9c8921ad5L;
    myConceptBehaviorIds[17] = 0x73b7c6f9c8921ad6L;
    myConceptBehaviorIds[18] = 0x73b7c6f9c8921ad7L;
  }

  @Deprecated
  @Override
  public BehaviorDescriptor getDescriptor(String fqName) {
    return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
  }

  @Nullable
  @Override
  public BHDescriptor getDescriptor(@NotNull SConceptId conceptId) {
    int behaviorIndex = Arrays.binarySearch(myConceptBehaviorIds, conceptId.getIdValue());
    switch (behaviorIndex) {
      case 0:
        return myIIncludeConcepts__BehaviorDescriptor;
      case 1:
        return myIncludeLanguage__BehaviorDescriptor;
      case 2:
        return myWebEditors__BehaviorDescriptor;
      case 3:
        return myNListFocus__BehaviorDescriptor;
      case 4:
        return myMapChild__BehaviorDescriptor;
      case 5:
        return myQueryReturnType__BehaviorDescriptor;
      case 6:
        return myInterfaceMethod__BehaviorDescriptor;
      case 7:
        return myMavenPom__BehaviorDescriptor;
      case 8:
        return myApache2_0__BehaviorDescriptor;
      case 9:
        return myPersistedConcepts__BehaviorDescriptor;
      case 10:
        return myIncludeConcepts__BehaviorDescriptor;
      case 11:
        return myGwtModule__BehaviorDescriptor;
      case 12:
        return myTokenValueLink__BehaviorDescriptor;
      case 13:
        return myCellModel_Link__BehaviorDescriptor;
      case 14:
        return myExcludeConcept__BehaviorDescriptor;
      case 15:
        return myIExcludeConcepts__BehaviorDescriptor;
      case 16:
        return myNodeFocus__BehaviorDescriptor;
      case 17:
        return myNewBeanCreationFocus__BehaviorDescriptor;
      case 18:
        return myDbRetrievedFocus__BehaviorDescriptor;
      default:
        return null;
    }
  }
}
