package org.campagnelab.circles.aspect.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class ExcludeConcept_BehaviorDescriptor extends ExcludeConcepts_BehaviorDescriptor implements IExcludeConcepts_BehaviorDescriptor {
  public Iterable<SNode> virtual_getConcepts_7466760769191571326(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.circles.aspect.structure.ExcludeConcept";
  }

}
