package org.campagnelab.circles.aspect.behavior;

/*Generated by MPS */

import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.Language;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class GwtModule_Behavior {
  public static List<SNode> call_usedModules_7317038553514089984(SNode __thisNode__) {
    return GwtModule__BehaviorDescriptor.usedModules_id6mblWKe2TS0(__thisNode__);
  }
  public static SNode call_getPersistedConcepts_3186401101630328236(SNode __thisNode__) {
    return GwtModule__BehaviorDescriptor.getPersistedConcepts_id2KSnIHI_GQG(__thisNode__);
  }
  public static Iterable<Language> call_getLanguages_1229736489878628000(SNode __thisNode__) {
    return GwtModule__BehaviorDescriptor.getLanguages_id14gTH9Qziqw(__thisNode__);
  }
  public static List<SNode> call_getLanguageNames_1229736489879089969(SNode __thisNode__) {
    return GwtModule__BehaviorDescriptor.getLanguageNames_id14gTH9Q_3cL(__thisNode__);
  }
  public static String call_getTargetPackageNameForLanguage_1229736489877529491(SAbstractConcept __thisConcept__, SNode language, String dotSubPackageName) {
    return GwtModule__BehaviorDescriptor.getTargetPackageNameForLanguage_id14gTH9Qv6ej(__thisConcept__, language, dotSubPackageName);
  }
  public static String call_getTargetPackageName_1229736489875241843(SAbstractConcept __thisConcept__, SNode node, String dotSubPackageName) {
    return GwtModule__BehaviorDescriptor.getTargetPackageName_id14gTH9QmnHN(__thisConcept__, node, dotSubPackageName);
  }
}
