package org.campagnelab.circles.aspect.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.Language;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class IncludeConcepts_BehaviorDescriptor extends ContributeConcepts_BehaviorDescriptor implements IIncludeConcepts_BehaviorDescriptor {
  public Iterable<SNode> virtual_getConcepts_1004539053072256506(SNode __thisNode__) {
    return null;
  }
  public Iterable<Language> virtual_getLanguages_1229736489878678534(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.circles.aspect.structure.IncludeConcepts";
  }

}
