package org.campagnelab.circles.aspect.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class NewBeanCreationFocus_Behavior {
  public static SNode call_getViewingConcept_8338352011214955998(SNode __thisNode__) {
    return NewBeanCreationFocus__BehaviorDescriptor.getViewingConcept_id7eRLJB8Cqnu(__thisNode__);
  }
}
