package org.campagnelab.circles.aspect.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public abstract class NodeFocus_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.circles.aspect.structure.NodeFocus";
  }

  public abstract String virtual_getTargetConceptName_2477299493866847209(SNode __thisNode__);
}
