package org.campagnelab.circles.aspect.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class PersistedConcepts_Behavior {
  public static SNode call_getModule_2477299493863826252(SNode __thisNode__) {
    return PersistedConcepts__BehaviorDescriptor.getModule_id29x8GeI0ydc(__thisNode__);
  }
  public static List<SNode> call_aggregationsIncludingIC_5228167051920110618(SAbstractConcept __thisConcept__, SNode acd) {
    return PersistedConcepts__BehaviorDescriptor.aggregationsIncludingIC_id4yebzJk6ngq(__thisConcept__, acd);
  }
  public static List<SNode> call_referencesIncludingIC_7319270224496693854(SAbstractConcept __thisConcept__, SNode acd) {
    return PersistedConcepts__BehaviorDescriptor.referencesIncludingIC_id6mjhnPMe19u(__thisConcept__, acd);
  }
}
