package org.campagnelab.circles.aspect.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support compilation of the legacy behavior descriptors before the language is rebuilt
 * This class is not involved in the actual method invocation
 */
@Deprecated
public class PersistedConcepts_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IIncludeConcepts_BehaviorDescriptor {
  public Iterable<SNode> virtual_getConcepts_1004539053072256506(SNode __thisNode__) {
    return null;
  }

  @Override
  public String getConceptFqName() {
    return "org.campagnelab.circles.aspect.structure.PersistedConcepts";
  }

}
