package org.campagnelab.circles.aspect.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import java.util.List;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class QueryReturnType_Behavior {
  public static SNode call_dbConceptType_5597880810755726761(SNode __thisNode__) {
    return QueryReturnType__BehaviorDescriptor.dbConceptType_id4QJEJ144xQD(__thisNode__);
  }
  public static List<SNode> call_getReturnTypes_5597880810755727451(SNode __thisNode__) {
    return QueryReturnType__BehaviorDescriptor.getReturnTypes_id4QJEJ144y1r(__thisNode__);
  }
}
