package org.campagnelab.circles.aspect.db;

/*Generated by MPS */


public enum CIRCLES_BASE_CONCEPTS {
  PROJECT() {
    public String dbClass() {
      return DbClassNameUtil.make("org.campagnelab.circles.model.structure.Project");
    }

  },
  MODULE() {
    public String dbClass() {
      return DbClassNameUtil.make("org.campagnelab.circles.model.structure.Module");
    }

  },
  MODEL() {
    public String dbClass() {
      return DbClassNameUtil.make("org.campagnelab.circles.model.structure.Model");
    }

  },
  LANGUAGE() {
    public String dbClass() {
      return DbClassNameUtil.make("org.campagnelab.circles.model.structure.Language");
    }

  },
  SOLUTION() {
    public String dbClass() {
      return DbClassNameUtil.make("org.campagnelab.circles.model.structure.Solution");
    }

  };

  public abstract String dbClass();
}
