package org.campagnelab.staging.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Collections;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xb42eb996b76a4e2dL, 0x81329278b4ff8107L, 0x2e0a72d3a5c50164L, "org.campagnelab.staging.structure.AddImportStatement"))) {
        return Collections.<ConceptEditor>singletonList(new AddImportStatement_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xb42eb996b76a4e2dL, 0x81329278b4ff8107L, 0x658b57cc0de14c3dL, "org.campagnelab.staging.structure.ChangeExtensionInfo"))) {
        return Collections.<ConceptEditor>singletonList(new ChangeExtensionInfo_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xb42eb996b76a4e2dL, 0x81329278b4ff8107L, 0x2e0a72d3a59db0e4L, "org.campagnelab.staging.structure.StageToAnnotation"))) {
        return Collections.<ConceptEditor>singletonList(new StageToAnnotation_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0xb42eb996b76a4e2dL, 0x81329278b4ff8107L, 0x2e0a72d3a5a0628aL, "org.campagnelab.staging.structure.StagingInfo"))) {
        return Collections.<ConceptEditor>singletonList(new StagingInfo_Editor());
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }



}
