package org.campagnelab.circles.model.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Collections;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x87c8043efece4ba6L, 0x9d133ef71e47af25L, 0xa886fa4c12864dL, "org.campagnelab.circles.model.structure.Language"))) {
        return Collections.<ConceptEditor>singletonList(new Language_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x87c8043efece4ba6L, 0x9d133ef71e47af25L, 0x53b437228f097e39L, "org.campagnelab.circles.model.structure.Model"))) {
        return Collections.<ConceptEditor>singletonList(new Model_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x87c8043efece4ba6L, 0x9d133ef71e47af25L, 0x53b437228f097e36L, "org.campagnelab.circles.model.structure.Module"))) {
        return Collections.<ConceptEditor>singletonList(new Module_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x87c8043efece4ba6L, 0x9d133ef71e47af25L, 0x53b437228f097e33L, "org.campagnelab.circles.model.structure.Project"))) {
        return Collections.<ConceptEditor>singletonList(new Project_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x87c8043efece4ba6L, 0x9d133ef71e47af25L, 0x230c8f0e4732e350L, "org.campagnelab.circles.model.structure.Root"))) {
        return Collections.<ConceptEditor>singletonList(new Root_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x87c8043efece4ba6L, 0x9d133ef71e47af25L, 0x4dafaaf0440c5a52L, "org.campagnelab.circles.model.structure.RootRef"))) {
        return Collections.<ConceptEditor>singletonList(new RootRef_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x87c8043efece4ba6L, 0x9d133ef71e47af25L, 0x226122c3adaad49aL, "org.campagnelab.circles.model.structure.SearchNodes"))) {
        return Collections.<ConceptEditor>singletonList(new SearchNodes_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x87c8043efece4ba6L, 0x9d133ef71e47af25L, 0xa886fa4c128650L, "org.campagnelab.circles.model.structure.Solution"))) {
        return Collections.<ConceptEditor>singletonList(new Solution_Editor());
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }



}
