package org.campagnelab.circles.model.web;

/*Generated by MPS */

import com.google.gwt.place.shared.WithTokenizers;
import com.google.gwt.place.shared.PlaceHistoryMapper;

@WithTokenizers(value = {ViewProject.Tokenizer.class, ViewModulePlace.Tokenizer.class, SearchNodesPlace.Tokenizer.class, ViewRoot.Tokenizer.class})
public interface AppPlaceHistoryMapper extends PlaceHistoryMapper {
}
