package org.campagnelab.circles.model.web;

/*Generated by MPS */

import com.orientechnologies.orient.core.record.impl.ODocument;

public class Attribute_DbToPojoHelper {
  public static void transfer(ODocument source, Attribute_Bean destination) {
    // transfer properties: 
    // transfer references: 
    // transfer children: 
  }

  public static Attribute_Bean transform(ODocument doc) {
    if (doc == null) {
      return null;
    }
    Attribute_Bean bean = new Attribute_Bean();
    Attribute_DbToPojoHelper.transfer(doc, bean);
    return bean;
  }
}
