package org.campagnelab.circles.model.web;

/*Generated by MPS */

import java.util.logging.Logger;

public class AttributeToWebModel {
  private static Logger logger = Logger.getLogger("AttributeToWebModel");

  public static Attribute_WebModel create(Attribute_Bean bean) {
    Attribute_WebModel model = (Attribute_WebModel) WebModelFactory.createWebModel(bean);
    return model;
  }
  public static void transfer(Attribute_Bean source, Attribute_WebModel destination) {
    if (source == null) {
      return;
    }
    BaseConceptToWebModel.transfer(source, destination);
    // transfer children: 
    // transfer references: 

  }

  public static Attribute_WebModel transform(Attribute_Bean bean, ClientFactoryInterface clientFactory) {
    if (bean == null) {
      return null;
    }
    Attribute_WebModel model = create(bean);
    if (model != null) {
      model.setClientFactory(clientFactory);
    }
    transfer(bean, model);
    return model;
  }
}
