package org.campagnelab.circles.model.web;

/*Generated by MPS */

import jetbrains.jetpad.model.children.HasParent;
import java.util.logging.Logger;
import jetbrains.jetpad.model.property.Property;
import jetbrains.jetpad.model.property.ValueProperty;
import jetbrains.jetpad.model.collections.list.ObservableList;
import jetbrains.jetpad.model.children.ChildList;

public class BaseConcept_WebModel extends HasParent {
  protected ClientFactoryInterface clientFactory;
  protected static Logger logger = Logger.getLogger("BaseConcept_WebModel");

  public void setClientFactory(ClientFactoryInterface cf) {
    this.clientFactory = cf;
  }
  public final Property<String> shortDescription = new ValueProperty();
  public final Property<String> alias = new ValueProperty();
  public final Property<String> virtualPackage = new ValueProperty();
  public ObservableList<Attribute_WebModel> smodelAttribute = new ChildList(this);

  public BaseConcept_WebModel() {

  }
}
