package org.campagnelab.circles.model.web;

/*Generated by MPS */

import java.util.logging.Logger;

public class BaseConceptToWebModel {
  private static Logger logger = Logger.getLogger("BaseConceptToWebModel");

  public static BaseConcept_WebModel create(BaseConcept_Bean bean) {
    BaseConcept_WebModel model = (BaseConcept_WebModel) WebModelFactory.createWebModel(bean);
    return model;
  }
  public static void transfer(BaseConcept_Bean source, BaseConcept_WebModel destination) {
    if (source == null) {
      return;
    }
    destination.shortDescription.set(source.shortDescription);
    destination.alias.set(source.alias);
    destination.virtualPackage.set(source.virtualPackage);
    // transfer children: 
    if (source.smodelAttribute != null) {
      for (Attribute_Bean childBean : source.smodelAttribute) {
        if (childBean != null) {
          Attribute_WebModel destChild = AttributeToWebModel.create(childBean);
          AttributeToWebModel.transfer(childBean, destChild);
          destination.smodelAttribute.add(destChild);
        }
      }
    }

    // transfer references: 

  }

  public static BaseConcept_WebModel transform(BaseConcept_Bean bean, ClientFactoryInterface clientFactory) {
    if (bean == null) {
      return null;
    }
    BaseConcept_WebModel model = create(bean);
    if (model != null) {
      model.setClientFactory(clientFactory);
    }
    transfer(bean, model);
    return model;
  }
}
