package org.campagnelab.circles.model.web;

/*Generated by MPS */

import jetbrains.jetpad.mapper.Mapper;
import org.webapp.languages.jetbrains_mps_lang_core.client.models.BaseConcept_WebModel;
import jetbrains.jetpad.mapper.gwt.WithElement;

public class BaseConcept_WebMapper extends Mapper<BaseConcept_WebModel, WithElement> {
  public BaseConcept_WebMapper(BaseConcept_WebModel model) {
    super(model, new BaseConcept_WebView());
  }

}
