package org.campagnelab.circles.model.web;

/*Generated by MPS */

import com.orientechnologies.orient.core.record.impl.ODocument;

public class ChildAttribute_DbToPojoHelper {
  public static void transfer(ODocument source, ChildAttribute_Bean destination) {
    Attribute_DbToPojoHelper.transfer(source, destination);
    // transfer properties: 
    destination.linkRole = source.field("linkRole");
    destination.linkId = source.field("linkId");
    // transfer references: 
    // transfer children: 
  }

  public static ChildAttribute_Bean transform(ODocument doc) {
    if (doc == null) {
      return null;
    }
    ChildAttribute_Bean bean = new ChildAttribute_Bean();
    ChildAttribute_DbToPojoHelper.transfer(doc, bean);
    return bean;
  }
}
