package org.campagnelab.circles.model.web;

/*Generated by MPS */

import com.google.gwt.user.client.rpc.AsyncCallback;
import java.util.List;

public interface DbGenericServiceAsync {
  public void getModule(String moduleId, AsyncCallback<Module_Bean> asyn);
  public void getSolution(String name, AsyncCallback<Solution_Bean> asyn);
  public void getProject(String projectName, AsyncCallback<Project_Bean> asyn);
  public void getModel(String modelId, AsyncCallback<Model_Bean> asyn);
  public void getRoot(String id, AsyncCallback<Root_Bean> asyn);
  public void getListRoot(String queryTerm, AsyncCallback<List<Root_Bean>> asyn);
  public void getListRootRef(String queryTerm, AsyncCallback<List<RootRef_Bean>> asyn);

}
