package org.campagnelab.circles.model.web;

/*Generated by MPS */

import com.orientechnologies.orient.core.record.impl.ODocument;

public class ExportScopePublic_DbToPojoHelper {
  public static void transfer(ODocument source, ExportScopePublic_Bean destination) {
    ExportScope_DbToPojoHelper.transfer(source, destination);
    // transfer properties: 
    // transfer references: 
    // transfer children: 
  }

  public static ExportScopePublic_Bean transform(ODocument doc) {
    if (doc == null) {
      return null;
    }
    ExportScopePublic_Bean bean = new ExportScopePublic_Bean();
    ExportScopePublic_DbToPojoHelper.transfer(doc, bean);
    return bean;
  }
}
