package org.campagnelab.circles.model.web;

/*Generated by MPS */

import java.io.Serializable;

public class ExportScopeModule_Bean extends ExportScope_Bean implements Serializable {
  public ExportScopeModule_Bean() {
  }
}
