package org.campagnelab.circles.model.web;

/*Generated by MPS */

import java.io.Serializable;

public class ExportScope_Bean extends NodeAttribute_Bean implements Serializable {
  public ExportScope_Bean() {
  }
}
