package org.campagnelab.circles.model.web;

/*Generated by MPS */

import com.orientechnologies.orient.core.record.impl.ODocument;

public class IDontApplyTypesystemRules_DbToPojoHelper {
  public static void transfer(ODocument source, IDontApplyTypesystemRules_Bean destination) {
    // transfer properties: 
    // transfer references: 
    // transfer children: 
  }

  public static IDontApplyTypesystemRules_Bean transform(ODocument doc) {
    if (doc == null) {
      return null;
    }
    IDontApplyTypesystemRules_Bean bean = new IDontApplyTypesystemRules_Bean();
    IDontApplyTypesystemRules_DbToPojoHelper.transfer(doc, bean);
    return bean;
  }
}
