package org.campagnelab.circles.model.web;

/*Generated by MPS */

import java.io.Serializable;

public class INamedConcept_Bean implements Serializable {
  public String name;
  public INamedConcept_Bean() {
  }
}
