package org.campagnelab.circles.model.web;

/*Generated by MPS */

import java.io.Serializable;

public class ISkipConstraintsChecking_Bean implements Serializable {
  public ISkipConstraintsChecking_Bean() {
  }
}
