package org.campagnelab.circles.model.web;

/*Generated by MPS */

import com.orientechnologies.orient.core.record.impl.ODocument;

public class IWrapper_DbToPojoHelper {
  public static void transfer(ODocument source, IWrapper_Bean destination) {
    // transfer properties: 
    // transfer references: 
    // transfer children: 
  }

  public static IWrapper_Bean transform(ODocument doc) {
    if (doc == null) {
      return null;
    }
    IWrapper_Bean bean = new IWrapper_Bean();
    IWrapper_DbToPojoHelper.transfer(doc, bean);
    return bean;
  }
}
