package org.campagnelab.circles.model.web;

/*Generated by MPS */

import java.util.logging.Logger;

public class LanguageToWebModel {
  private static Logger logger = Logger.getLogger("LanguageToWebModel");

  public static Language_WebModel create(Language_Bean bean) {
    Language_WebModel model = (Language_WebModel) WebModelFactory.createWebModel(bean);
    return model;
  }
  public static void transfer(Language_Bean source, Language_WebModel destination) {
    if (source == null) {
      return;
    }
    ModuleToWebModel.transfer(source, destination);
    destination.name.set(source.name);
    // transfer children: 
    // transfer references: 

  }

  public static Language_WebModel transform(Language_Bean bean, ClientFactoryInterface clientFactory) {
    if (bean == null) {
      return null;
    }
    Language_WebModel model = create(bean);
    if (model != null) {
      model.setClientFactory(clientFactory);
    }
    transfer(bean, model);
    return model;
  }
}
