package org.campagnelab.circles.model.web;

/*Generated by MPS */

import com.orientechnologies.orient.core.record.impl.ODocument;

public class Language_DbToPojoHelper {
  public static void transfer(ODocument source, Language_Bean destination) {
    Module_DbToPojoHelper.transfer(source, destination);
    // transfer properties: 
    destination.name = source.field("name");
    // transfer references: 
    // transfer children: 
  }

  public static Language_Bean transform(ODocument doc) {
    if (doc == null) {
      return null;
    }
    Language_Bean bean = new Language_Bean();
    Language_DbToPojoHelper.transfer(doc, bean);
    return bean;
  }
}
