package org.campagnelab.circles.model.web;

/*Generated by MPS */

import java.util.logging.Logger;

public class LinkAttributeToWebModel {
  private static Logger logger = Logger.getLogger("LinkAttributeToWebModel");

  public static LinkAttribute_WebModel create(LinkAttribute_Bean bean) {
    LinkAttribute_WebModel model = (LinkAttribute_WebModel) WebModelFactory.createWebModel(bean);
    return model;
  }
  public static void transfer(LinkAttribute_Bean source, LinkAttribute_WebModel destination) {
    if (source == null) {
      return;
    }
    AttributeToWebModel.transfer(source, destination);
    destination.linkRole.set(source.linkRole);
    destination.linkId.set(source.linkId);
    // transfer children: 
    // transfer references: 

  }

  public static LinkAttribute_WebModel transform(LinkAttribute_Bean bean, ClientFactoryInterface clientFactory) {
    if (bean == null) {
      return null;
    }
    LinkAttribute_WebModel model = create(bean);
    if (model != null) {
      model.setClientFactory(clientFactory);
    }
    transfer(bean, model);
    return model;
  }
}
