package org.campagnelab.circles.model.web;

/*Generated by MPS */

import jetbrains.jetpad.mapper.Mapper;
import jetbrains.jetpad.mapper.Synchronizers;
import jetbrains.jetpad.mapper.gwt.DomUtil;
import jetbrains.jetpad.mapper.MapperFactory;
import org.webapp.languages.jetbrains_mps_lang_core.client.models.BaseConcept_WebModel;

public class Model_WebMapper extends Mapper<Model_WebModel, Model_WebView> {

  public Model_WebMapper(Model_WebModel model) {
    super(model, new Model_WebView());
    // Connect events to view here 
  }
  @Override
  protected void registerSynchronizers(Mapper.SynchronizersConfiguration conf) {
    super.registerSynchronizers(conf);
    //  Insertion point for add synchronizer: 
    conf.add(Synchronizers.forPropsTwoWay(getSource().name, DomUtil.editableTextOf(getTarget().name)));

    conf.add(Synchronizers.forObservableRole(this, getSource().nodes, DomUtil.withAnimatedElementChildren(getTarget().nodes), new MapperFactory() {
      public Mapper createMapper(Object model) {
        // need to find a way to use the global WebModelFactory, not the one from a specific module.  
        return WebModelFactory.createMapper((BaseConcept_WebModel) model);
      }
    }));
    //  map references like %circles% -> name 



  }

}
