package org.campagnelab.circles.model.web;

/*Generated by MPS */

import java.io.Serializable;
import java.util.List;
import org.webapp.languages.jetbrains_mps_lang_core.shared.beans.BaseConcept_Bean;

public class Model_Bean extends Root_Bean implements Serializable {
  public String name;
  public List<BaseConcept_Bean> nodes;
  public Model_Bean() {
  }
}
