package org.campagnelab.circles.model.web;

/*Generated by MPS */

import com.orientechnologies.orient.core.record.impl.ODocument;
import java.util.List;
import com.orientechnologies.orient.core.db.record.OIdentifiable;
import java.util.ArrayList;

public class Module_DbToPojoHelper {
  public static void transfer(ODocument source, Module_Bean destination) {
    Root_DbToPojoHelper.transfer(source, destination);
    // transfer properties: 
    destination.name = source.field("name");
    destination.moduleId = source.field("moduleId");
    // transfer references: 
    // transfer children: 
    {
      List<OIdentifiable> childrenValues = source.field("models");
      if (childrenValues != null) {
        destination.models = new ArrayList<Model_Bean>();
        for (OIdentifiable childDoc : childrenValues) {
          if (childDoc != null) {
            //  we use reflection here because we need to convert the db class to  
            //  a concrete POJO class to correctly transfer its data: 
            destination.models.add((Model_Bean) ReflectionHelper.transformToPojo((ODocument) childDoc));
          }
        }
      }
    }
  }

  public static Module_Bean transform(ODocument doc) {
    if (doc == null) {
      return null;
    }
    Module_Bean bean = new Module_Bean();
    Module_DbToPojoHelper.transfer(doc, bean);
    return bean;
  }
}
