package org.campagnelab.circles.model.web;

/*Generated by MPS */

import com.orientechnologies.orient.core.record.impl.ODocument;

public class NodeAttribute_DbToPojoHelper {
  public static void transfer(ODocument source, NodeAttribute_Bean destination) {
    Attribute_DbToPojoHelper.transfer(source, destination);
    // transfer properties: 
    // transfer references: 
    // transfer children: 
  }

  public static NodeAttribute_Bean transform(ODocument doc) {
    if (doc == null) {
      return null;
    }
    NodeAttribute_Bean bean = new NodeAttribute_Bean();
    NodeAttribute_DbToPojoHelper.transfer(doc, bean);
    return bean;
  }
}
