package org.campagnelab.circles.model.web;

/*Generated by MPS */

import com.orientechnologies.orient.core.record.impl.ODocument;
import java.util.List;
import com.orientechnologies.orient.core.db.record.OIdentifiable;
import java.util.ArrayList;

public class Project_DbToPojoHelper {
  public static void transfer(ODocument source, Project_Bean destination) {
    Root_DbToPojoHelper.transfer(source, destination);
    // transfer properties: 
    destination.name = source.field("name");
    // transfer references: 
    // transfer children: 
    {
      List<OIdentifiable> childrenValues = source.field("modules");
      if (childrenValues != null) {
        destination.modules = new ArrayList<Module_Bean>();
        for (OIdentifiable childDoc : childrenValues) {
          if (childDoc != null) {
            //  we use reflection here because we need to convert the db class to  
            //  a concrete POJO class to correctly transfer its data: 
            destination.modules.add((Module_Bean) ReflectionHelper.transformToPojo((ODocument) childDoc));
          }
        }
      }
    }
  }

  public static Project_Bean transform(ODocument doc) {
    if (doc == null) {
      return null;
    }
    Project_Bean bean = new Project_Bean();
    Project_DbToPojoHelper.transfer(doc, bean);
    return bean;
  }
}
