package org.campagnelab.circles.model.web;

/*Generated by MPS */

import java.util.logging.Logger;

public class ProjectToWebModel {
  private static Logger logger = Logger.getLogger("ProjectToWebModel");

  public static Project_WebModel create(Project_Bean bean) {
    Project_WebModel model = (Project_WebModel) WebModelFactory.createWebModel(bean);
    return model;
  }
  public static void transfer(Project_Bean source, Project_WebModel destination) {
    if (source == null) {
      return;
    }
    RootToWebModel.transfer(source, destination);
    destination.name.set(source.name);
    // transfer children: 
    if (source.modules != null) {
      for (Module_Bean childBean : source.modules) {
        if (childBean != null) {
          Module_WebModel destChild = ModuleToWebModel.create(childBean);
          ModuleToWebModel.transfer(childBean, destChild);
          destination.modules.add(destChild);
        }
      }
    }

    // transfer references: 

  }

  public static Project_WebModel transform(Project_Bean bean, ClientFactoryInterface clientFactory) {
    if (bean == null) {
      return null;
    }
    Project_WebModel model = create(bean);
    if (model != null) {
      model.setClientFactory(clientFactory);
    }
    transfer(bean, model);
    return model;
  }
}
