package org.campagnelab.circles.model.web;

/*Generated by MPS */

import java.io.Serializable;
import java.util.List;

public class Project_Bean extends Root_Bean implements Serializable {
  public String name;
  public List<Module_Bean> modules;
  public Project_Bean() {
  }
}
