package org.campagnelab.circles.model.web;

/*Generated by MPS */

import com.orientechnologies.orient.core.record.impl.ODocument;

public class PropertyAttribute_DbToPojoHelper {
  public static void transfer(ODocument source, PropertyAttribute_Bean destination) {
    Attribute_DbToPojoHelper.transfer(source, destination);
    // transfer properties: 
    destination.propertyName = source.field("propertyName");
    destination.propertyId = source.field("propertyId");
    // transfer references: 
    // transfer children: 
  }

  public static PropertyAttribute_Bean transform(ODocument doc) {
    if (doc == null) {
      return null;
    }
    PropertyAttribute_Bean bean = new PropertyAttribute_Bean();
    PropertyAttribute_DbToPojoHelper.transfer(doc, bean);
    return bean;
  }
}
