package org.campagnelab.circles.model.web;

/*Generated by MPS */

import org.webapp.languages.jetbrains_mps_lang_core.shared.beans.BaseConcept_Bean;
import java.io.Serializable;

public class RootRef_Bean extends BaseConcept_Bean implements Serializable {
  public String name;
  public String id;
  public RootRef_Bean() {
  }
}
