package org.campagnelab.circles.model.web;

/*Generated by MPS */

import com.orientechnologies.orient.core.record.impl.ODocument;

public class Root_DbToPojoHelper {
  public static void transfer(ODocument source, Root_Bean destination) {
    
    // ignore concept interface ;
    // transfer properties: 
    destination.name = source.field("name");
    destination.id = source.field("id");
    destination.svgRendering = source.field("svgRendering");
    // transfer references: 
    // transfer children: 
  }

  public static Root_Bean transform(ODocument doc) {
    if (doc == null) {
      return null;
    }
    Root_Bean bean = new Root_Bean();
    Root_DbToPojoHelper.transfer(doc, bean);
    return bean;
  }
}
