package org.campagnelab.circles.model.web;

/*Generated by MPS */

import java.util.logging.Logger;

public class RootRefToWebModel {
  private static Logger logger = Logger.getLogger("RootRefToWebModel");

  public static RootRef_WebModel create(RootRef_Bean bean) {
    RootRef_WebModel model = (RootRef_WebModel) WebModelFactory.createWebModel(bean);
    return model;
  }
  public static void transfer(RootRef_Bean source, RootRef_WebModel destination) {
    if (source == null) {
      return;
    }
    BaseConceptToWebModel.transfer(source, destination);
    
    // ignore interface ;
    destination.name.set(source.name);
    destination.id.set(source.id);
    // transfer children: 
    // transfer references: 

  }

  public static RootRef_WebModel transform(RootRef_Bean bean, ClientFactoryInterface clientFactory) {
    if (bean == null) {
      return null;
    }
    RootRef_WebModel model = create(bean);
    if (model != null) {
      model.setClientFactory(clientFactory);
    }
    transfer(bean, model);
    return model;
  }
}
