package org.campagnelab.circles.model.web;

/*Generated by MPS */

import org.webapp.languages.jetbrains_mps_lang_core.client.models.BaseConcept_WebModel;
import java.util.logging.Logger;
import jetbrains.jetpad.model.property.Property;
import jetbrains.jetpad.model.property.ValueProperty;

public class RootRef_WebModel extends BaseConcept_WebModel {
  protected ClientFactoryInterface clientFactory;
  protected static Logger logger = Logger.getLogger("RootRef_WebModel");

  public void setClientFactory(ClientFactoryInterface cf) {
    this.clientFactory = cf;
  }
  public final Property<String> name = new ValueProperty();
  public final Property<String> id = new ValueProperty();

  public RootRef_WebModel() {

  }
  public void link_View() {
    logger.info("clicked " + "View");
    clientFactory.getPlaceController().goTo(new ViewRoot(this.id.get()));
  }
}
