package org.campagnelab.circles.model.web;

/*Generated by MPS */

import org.webapp.languages.jetbrains_mps_lang_core.client.models.BaseConcept_WebModel;
import java.util.logging.Logger;
import jetbrains.jetpad.model.property.Property;
import jetbrains.jetpad.model.property.ValueProperty;
import jetbrains.jetpad.model.collections.list.ObservableList;
import jetbrains.jetpad.model.children.ChildList;

public abstract class SearchNodes_WebModel extends BaseConcept_WebModel {
  protected ClientFactoryInterface clientFactory;
  protected static Logger logger = Logger.getLogger("SearchNodes_WebModel");

  public void setClientFactory(ClientFactoryInterface cf) {
    this.clientFactory = cf;
  }
  public final Property<String> searchTerm = new ValueProperty();
  public ObservableList<RootRef_WebModel> results = new ChildList(this);

  public SearchNodes_WebModel() {

  }
  public void link_Search() {
    logger.info("clicked " + "Search");
    clientFactory.getPlaceController().goTo(new SearchNodesPlace(this.searchTerm.get()));
  }
  public void link_Playground() {
    logger.info("clicked " + "Playground");
    clientFactory.getPlaceController().goTo(new ViewProject());
  }
  public void link_clearAll() {
    logger.info("clicked " + "clear all");
    this.???();
  }
public abstract void clearAll();
}
