package org.campagnelab.circles.model.web;

/*Generated by MPS */

import java.util.logging.Logger;

public class SearchNodesToWebModel {
  private static Logger logger = Logger.getLogger("SearchNodesToWebModel");

  public static SearchNodes_WebModel create(SearchNodes_Bean bean) {
    SearchNodes_WebModel model = (SearchNodes_WebModel) WebModelFactory.createWebModel(bean);
    return model;
  }
  public static void transfer(SearchNodes_Bean source, SearchNodes_WebModel destination) {
    if (source == null) {
      return;
    }
    BaseConceptToWebModel.transfer(source, destination);
    destination.searchTerm.set(source.searchTerm);
    // transfer children: 
    if (source.results != null) {
      for (RootRef_Bean childBean : source.results) {
        if (childBean != null) {
          RootRef_WebModel destChild = RootRefToWebModel.create(childBean);
          RootRefToWebModel.transfer(childBean, destChild);
          destination.results.add(destChild);
        }
      }
    }

    // transfer references: 

  }

  public static SearchNodes_WebModel transform(SearchNodes_Bean bean, ClientFactoryInterface clientFactory) {
    if (bean == null) {
      return null;
    }
    SearchNodes_WebModel model = create(bean);
    if (model != null) {
      model.setClientFactory(clientFactory);
    }
    transfer(bean, model);
    return model;
  }
}
