package org.campagnelab.circles.model.web;

/*Generated by MPS */

import java.util.logging.Logger;
import jetbrains.jetpad.model.property.Property;
import jetbrains.jetpad.model.property.ValueProperty;

public class SideTransformInfo_WebModel extends NodeAttribute_WebModel {
  protected ClientFactoryInterface clientFactory;
  protected static Logger logger = Logger.getLogger("SideTransformInfo_WebModel");

  public void setClientFactory(ClientFactoryInterface cf) {
    this.clientFactory = cf;
  }
  public final Property<String> side = new ValueProperty();
  public final Property<String> cellId = new ValueProperty();
  public final Property<String> anchorTag = new ValueProperty();

  public SideTransformInfo_WebModel() {

  }
}
