package org.campagnelab.circles.model.web;

/*Generated by MPS */

import java.io.Serializable;

public class SideTransformInfo_Bean extends NodeAttribute_Bean implements Serializable {
  public String side;
  public String cellId;
  public String anchorTag;
  public SideTransformInfo_Bean() {
  }
}
