package org.campagnelab.circles.model.web;

/*Generated by MPS */

import java.util.logging.Logger;
import jetbrains.jetpad.model.property.Property;
import jetbrains.jetpad.model.property.ValueProperty;

public class Solution_WebModel extends Module_WebModel {
  protected ClientFactoryInterface clientFactory;
  protected static Logger logger = Logger.getLogger("Solution_WebModel");

  public void setClientFactory(ClientFactoryInterface cf) {
    this.clientFactory = cf;
  }
  public final Property<String> name = new ValueProperty();

  public Solution_WebModel() {

  }
}
