package org.campagnelab.circles.model.web;

/*Generated by MPS */

import java.util.logging.Logger;

public class SolutionToWebModel {
  private static Logger logger = Logger.getLogger("SolutionToWebModel");

  public static Solution_WebModel create(Solution_Bean bean) {
    Solution_WebModel model = (Solution_WebModel) WebModelFactory.createWebModel(bean);
    return model;
  }
  public static void transfer(Solution_Bean source, Solution_WebModel destination) {
    if (source == null) {
      return;
    }
    ModuleToWebModel.transfer(source, destination);
    destination.name.set(source.name);
    // transfer children: 
    // transfer references: 

  }

  public static Solution_WebModel transform(Solution_Bean bean, ClientFactoryInterface clientFactory) {
    if (bean == null) {
      return null;
    }
    Solution_WebModel model = create(bean);
    if (model != null) {
      model.setClientFactory(clientFactory);
    }
    transfer(bean, model);
    return model;
  }
}
