package org.campagnelab.circles.model.web;

/*Generated by MPS */

import java.util.logging.Logger;

public class SuppressErrorsAnnotationToWebModel {
  private static Logger logger = Logger.getLogger("SuppressErrorsAnnotationToWebModel");

  public static SuppressErrorsAnnotation_WebModel create(SuppressErrorsAnnotation_Bean bean) {
    SuppressErrorsAnnotation_WebModel model = (SuppressErrorsAnnotation_WebModel) WebModelFactory.createWebModel(bean);
    return model;
  }
  public static void transfer(SuppressErrorsAnnotation_Bean source, SuppressErrorsAnnotation_WebModel destination) {
    if (source == null) {
      return;
    }
    NodeAttributeToWebModel.transfer(source, destination);
    
    // ignore interface ;
    // transfer children: 
    // transfer references: 

  }

  public static SuppressErrorsAnnotation_WebModel transform(SuppressErrorsAnnotation_Bean bean, ClientFactoryInterface clientFactory) {
    if (bean == null) {
      return null;
    }
    SuppressErrorsAnnotation_WebModel model = create(bean);
    if (model != null) {
      model.setClientFactory(clientFactory);
    }
    transfer(bean, model);
    return model;
  }
}
