package org.campagnelab.circles.model.web;

/*Generated by MPS */

import com.google.gwt.place.shared.Place;
import java.util.logging.Logger;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceTokenizer;

public class ViewRoot extends Place implements GenericPlace {
  private static Logger logger = Logger.getLogger("ViewRoot");

  private String token_id;
  public ViewRoot(String token_id) {
    this.token_id = token_id;
  }
  public String getToken_id() {
    return token_id;
  }
  public boolean hasAllTokens() {
    boolean result = true;
    result &= getToken_id() != null;
    return result;
  }
  @Override
  public Activity getActivity(ClientFactory clientFactory) {
    logger.info("getActivity for Place=" + "ViewRoot");
    return new ViewRootActivity(this, clientFactory);
  }

  public static class Tokenizer implements PlaceTokenizer<ViewRoot> {
    private static Logger logger = Logger.getLogger("Tokenizer");
    @Override
    public String getToken(ViewRoot place) {
      StringBuffer result = new StringBuffer();
      result.append("id");
      result.append(":");
      // TODO obtain the value of the token from the WebModel field.  
      result.append(place.getToken_id());
      logger.info("tokens=" + result);
      return result.toString();
    }
    @Override
    public ViewRoot getPlace(String token) {
      logger.info("getPlace token=" + token);
      String[] tokens = token.split(":");
      return new ViewRoot(tokens[1]);
    }
  }

}
