package org.campagnelab.circles.model.web;

/*Generated by MPS */

import com.google.gwt.place.shared.Place;
import java.util.logging.Logger;
import com.google.gwt.activity.shared.Activity;
import com.google.gwt.place.shared.PlaceTokenizer;

public class ViewProject extends Place implements GenericPlace {
  private static Logger logger = Logger.getLogger("ViewProject");

  public ViewProject() {
  }
  public boolean hasAllTokens() {
    boolean result = true;
    return result;
  }
  @Override
  public Activity getActivity(ClientFactory clientFactory) {
    logger.info("getActivity for Place=" + "ViewProject");
    return new ViewProjectActivity(this, clientFactory);
  }

  public static class Tokenizer implements PlaceTokenizer<ViewProject> {
    private static Logger logger = Logger.getLogger("Tokenizer");
    @Override
    public String getToken(ViewProject place) {
      StringBuffer result = new StringBuffer();
      logger.info("tokens=" + result);
      return result.toString();
    }
    @Override
    public ViewProject getPlace(String token) {
      logger.info("getPlace token=" + token);
      String[] tokens = token.split(":");
      return new ViewProject();
    }
  }

}
