package org.campagnelab.circles.model.web;

/*Generated by MPS */

import com.google.gwt.activity.shared.AbstractActivity;
import com.google.gwt.user.client.ui.HTML;
import java.util.logging.Logger;
import com.google.gwt.user.client.ui.AcceptsOneWidget;
import com.google.gwt.event.shared.EventBus;

public class ViewProjectActivity extends AbstractActivity {
  protected final ClientFactory clientFactory;
  protected Project_WebModel model;
  protected Project_WebMapper mapper;
  protected HTML htmlWrapper = new HTML("<div/>");
  protected Logger logger = Logger.getLogger("ViewProjectActivity");

  public ViewProjectActivity(ViewProject place, ClientFactory factory) {
    // Get the factory reference 
    this.clientFactory = factory;
    logger.info("Creating activity" + "ViewProjectActivity");
    model = new Project_WebModelImpl();
    // initialize properties from tokens if needed: 
    model.setClientFactory(clientFactory);
    mapper = new Project_WebMapper(model);
    mapper.attachRoot();
    htmlWrapper.getElement().appendChild(mapper.getTarget().getElement());

  }
  /**
   * Only used in MPS generator templates.
   */
  protected ViewProjectActivity() {
    clientFactory = null;
  }
  @Override
  public String mayStop() {
    //  do not ask for confirmation when stopping 
    return null;
  }
  @Override
  public void onStop() {
    super.onStop();
  }
  @Override
  public void start(AcceptsOneWidget panel, EventBus eventBus) {
    // Attach this view to the application container 
    // sds $("#main").append 
    assert clientFactory != null : "NULL clientFactory";
    panel.setWidget(htmlWrapper);
    logger.info("Starting activity" + "ViewProjectActivity");
  }
}
