package org.campagnelab.staging.behavior;

/*Generated by MPS */

import java.util.List;
import org.jetbrains.mps.openapi.model.SNode;

/**
 * Will be removed after 3.3
 * Need to support the legacy static direct method calls
 */
@Deprecated
public class StagingInfo_Behavior {
  public static List<String> call_imports_3317590328857310599(SNode __thisNode__) {
    return StagingInfo__BehaviorDescriptor.imports_id2SasHe_NVm7(__thisNode__);
  }
}
