package org.campagnelab.circles.persistence.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptDatabase = new ConceptDescriptorBuilder("org.campagnelab.circles.persistence.structure.Database", MetaIdFactory.conceptId(0x8202d3ebbfe04fb5L, 0x9544c67c5faa531dL, 0x2970c96b0e706973L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(2986108014587570548L, "url"), new ConceptDescriptorBuilder.Prop(4824635715685243887L, "user"), new ConceptDescriptorBuilder.Prop(4824635715685243890L, "password")).properties("url", "user", "password").create();
  /*package*/ final ConceptDescriptor myConceptExclusionRule = new ConceptDescriptorBuilder("org.campagnelab.circles.persistence.structure.ExclusionRule", MetaIdFactory.conceptId(0x8202d3ebbfe04fb5L, 0x9544c67c5faa531dL, 0x42f48c9f1414cf66L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(4824635715685240679L, "concept", MetaIdFactory.conceptId(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0x1103553c5ffL), false)).references("concept").alias("exclude", "Exclude Concepts From Persistence").create();
  /*package*/ final ConceptDescriptor myConceptIncludeConcept = new ConceptDescriptorBuilder("org.campagnelab.circles.persistence.structure.IncludeConcept", MetaIdFactory.conceptId(0x8202d3ebbfe04fb5L, 0x9544c67c5faa531dL, 0x42f48c9f1414cf69L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(4824635715685240682L, "concep", MetaIdFactory.conceptId(0xc72da2b97cce4447L, 0x8389f407dc1158b7L, 0x1103553c5ffL), false)).references("concep").alias("include", "Include Concepts For Persistence").create();
  /*package*/ final ConceptDescriptor myConceptPersistedConcepts = new ConceptDescriptorBuilder("org.campagnelab.circles.persistence.structure.PersistedConcepts", MetaIdFactory.conceptId(0x8202d3ebbfe04fb5L, 0x9544c67c5faa531dL, 0x42f48c9f1414cf63L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).childDescriptors(new ConceptDescriptorBuilder.Link(4824635715685240684L, "inclusionRules", MetaIdFactory.conceptId(0x8202d3ebbfe04fb5L, 0x9544c67c5faa531dL, 0x42f48c9f1414cf69L), true, true, false)).children(new String[]{"inclusionRules"}, new boolean[]{true}).create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptDatabase, myConceptExclusionRule, myConceptIncludeConcept, myConceptPersistedConcepts);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0i, conceptFqName)) {
      case 0:
        return myConceptDatabase;
      case 1:
        return myConceptExclusionRule;
      case 2:
        return myConceptIncludeConcept;
      case 3:
        return myConceptPersistedConcepts;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0i = new String[]{"org.campagnelab.circles.persistence.structure.Database", "org.campagnelab.circles.persistence.structure.ExclusionRule", "org.campagnelab.circles.persistence.structure.IncludeConcept", "org.campagnelab.circles.persistence.structure.PersistedConcepts"};
}
