package org.campagnelab.circles.aspect.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class UserMethodReference_Constraints extends BaseConstraintsDescriptor {
  public UserMethodReference_Constraints() {
    super(MetaIdFactory.conceptId(0x8c40f9f4b3bd42d0L, 0x8b658e644273493cL, 0x4c2903f1016e47e7L));
  }
}
