package org.campagnelab.circles.mockup.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.descriptor.EditorAspectDescriptor;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;

public class EditorAspectDescriptorImpl implements EditorAspectDescriptor {

  public Collection<ConceptEditor> getEditors(ConceptDescriptor descriptor) {
    switch (Arrays.binarySearch(stringSwitchCases_xbvbvu_a0a0b, descriptor.getConceptFqName())) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Circle_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new CircleContainer_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new CircleRef_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Dashboard_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }
  public Collection<ConceptEditorComponent> getEditorComponents(ConceptDescriptor descriptor, String editorComponentId) {
    return Collections.<ConceptEditorComponent>emptyList();
  }


  private static String[] stringSwitchCases_xbvbvu_a0a0b = new String[]{"org.campagnelab.circles.mockup.structure.Circle", "org.campagnelab.circles.mockup.structure.CircleContainer", "org.campagnelab.circles.mockup.structure.CircleRef", "org.campagnelab.circles.mockup.structure.Dashboard"};
}
