package org.webapp.languages.jetbrains_mps_lang_core.client.models;

/*Generated by MPS */

import java.io.Serializable;

public class Attribute_WebModel implements Serializable {
  public Attribute_WebModel() {
  }
}
